### ISSUE TITLE
Installation did not work

### ISSUE THREAD

**Issue by BenBals** [hpi-swa-teaching/OhmPrettyPrint#107]
Dear Ohm-Team,

I just tried to install your awesome project as the original pretty printer sucks.

When I ran the Metacello code from your README, I got an error saying "Could not resolve BaselineOfOhmPrettyPrint" and a "subscript out of bounds" error.

I suggest you use code like this. This installed fine for me.

```smalltalk
Metacello new
    baseline: 'OhmPrettyPrint';
    repository: 'github://HPI-SWA-Teaching/OhmPrettyPrint:dev/packages';
    onConflict: [:ex | ex allow];
    get;
    load
```

**Comment by BenBals** [comment]
Also, how do I pretty print with omega?

**Comment by Paula-Kli** [comment]
Dear Ben,

thanks for the hint with the Readme!

Using your code in a new image the 'omegaPrint'-Button in the image was without functionality but this code worked for me:
```smalltalk
Metacello new
    baseline: 'OhmPrettyPrint';
    repository: 'github://HPI-SWA-Teaching/OhmPrettyPrint:dev/packages';
    load
```

When you installed omegaPrint there should be a button in your browser or other CodeHolder right next to the prettyPrint Button. Maybe just try again to install it since we changed the baseline yesterday.

**Comment by BenBals** [comment]
Thanks, I ran your snippet, but can't see a difference. I saw the button yesterday. How do I confirm the installation worked?

Also consider adding the following method to your Baseline. Otherwise Metacello will not update your project properly. It will just see: "Well I need Omega, but I have Omega so everything is fine".

```smalltalk
projectClass

	^ Smalltalk
		at: #MetacelloCypressBaselineProject
		ifAbsent: [ super projectClass ]
```

**Comment by Paula-Kli** [comment]
Thanks for the hint we will consider it!

what do you mean by saying "How do I confirm the installation worked?". Opening a browser, do you see the button omegaPrint?

**Comment by BenBals** [comment]
Yes, I see it.

**Comment by Paula-Kli** [comment]
So than you should be able to click on it and it will prettify your code. Just the same as PrettyPrint it does just prettier ;)
