### ISSUE TITLE
Fallunterscheidungen

### ISSUE THREAD

**Issue by Paula-Kli** [hpi-swa-teaching/OhmPrettyPrint#131]
Wenn wir verschiedene Fälle haben, je nachdem wie viele Kinder wir haben, sollten wir die einzelnen Fälle benennen und in extra Methoden tun.

```smalltalk
KeywordMessageSend:with:and:
ifEmpty: ...
1Kind: keywordMessageSingleSegment
mehrereKinder: keywordMessageMultipleSegments
```

**Comment by felixauringer** [comment]
Prinzipiell richtig, ich habe es aber gerade nicht geschafft das ordentlich umzusetzen. Die betroffenen Methoden sind:
- `KeywordMessage:with:`
- `keywordMessageWith:and:`
Das Problem bei der Auslagerung auf das ich gestossen bin ist, dass man fuer den Aufruf wegen den Argumenten locker 3 Zeilen braucht und dann bleibt die Methode ziemlich genau gleich lang, man hat aber eine mehr.

**Comment by Paula-Kli** [comment]
Zumindest in `keywordMessageWith:and:` könnte man das ja als Liste mit Receiver und segments children übergeben und hätte nur ein Argument aber wir haben grad mit der Benennung überlegt und sind auf keine sinnvolle Idee gekommen
