### ISSUE TITLE
BlockLiteralNormal

### ISSUE THREAD

**Issue by Paula-Kli** [hpi-swa-teaching/OhmPrettyPrint#132]

**Comment by T4rikA** [comment]
Ich glaube diese Methode bekommen wir nicht schöner hin, alles was in der Methode ist brauchen wir.
Wir haben 3 Methodenaufrufe und berechnen uns davor unsere values.

**Comment by felixauringer** [comment]
Ich glaube wir kriegen es nicht kuerzer hin. Weil wir aber doch recht viel in Methoden ausgelagert haben, finde ich die Methode ganz verstaendlich (darum geht es ja)

**Comment by Paula-Kli** [comment]
Sieht schon deutlich besser aus, als ich das Issue geöffnet habe!
