### ISSUE TITLE
Test fuer Expression fehlt

### ISSUE THREAD

**Issue by felixauringer** [hpi-swa-teaching/OhmPrettyPrint#144]
Wir haben bisher immer, wenn wir ein Knoten mit  case-Label getestet haben auch die anderen Faelle getestet (die Testklasse wurde ja sowieso gebraucht). `Expression_base` ist der einzige Fall in dem wir das nicht machen und das sollten wir noch nachholgen.

**Comment by T4rikA** [comment]
Würde ich wiedersprechen, da wir dort einfach `KeywordMessageSend` testen würden und dafür schon Tests haben. Ansonsten würden wir diese ja einfach doppeln oder?

**Comment by felixauringer** [comment]
Wieso haben wir dann zum Beispiel fuer `ObjectArrayLiteralElement_finalExpression` oder `PragmaValues_unary` Tests? Ist das nicht genau derselbe Fall?

**Comment by PatriciaSowa** [comment]
Ja aber die starten von anderen Regeln.
Dadurch kann doch auch etwas kaputt gehen oder?

**Comment by felixauringer** [comment]
Hatte ich auch ueberlegt und mehr Tests sind ja nie 

> Ja aber die starten von anderen Regeln.
> Dadurch kann doch auch etwas kaputt gehen oder?

Man muss sich schon Muehe geben, aber moeglich ist es bestimmt und dafuer ist ein Test dann ganz nuetzlich
