### ISSUE TITLE
CodeHolder extension dokumentieren

### ISSUE THREAD

**Issue by felixauringer** [hpi-swa-teaching/OhmPrettyPrint#153]
Da wir fuer den CodeHolder keinen Klassenkommentar erstellen koennen, sollten wir auf jeden Fall irgendwo im Wiki erwaehnen, dass wir da ne Extension haben. Ich glaube die findet man sonst nie.

**Comment by Paula-Kli** [comment]
Ist kurz im Wiki dokumentiert
