### ISSUE TITLE
Combine multiple self calls into cascade

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/OhmPrettyPrint#31]
I think it would be really helpful if Pretty Printing could combine multiple calls to `self` into a single cascade.

i.e.:
``` Smalltalk
self foo: bar.
self foobar.
```
would become:
``` Smalltalk
self
    foo: bar;
    foobar.
```

I think this would make my code much clearer and easier to read. Furthermore I wouldn't have to think about how many statements I want to send to `self` before starting to write my code.

**Comment by T4rikA** [comment]
At the moment this functionality is not in the focus of the project, for the very moment it should only be about formatting and not changing the cst.
