### ISSUE TITLE
Leerzeichen vor Circumflex (1)

### ISSUE THREAD

**Issue by Paula-Kli** [hpi-swa-teaching/OhmPrettyPrint#34]
Bei einem FinalStatement wird vor dem Circumflex (^) ein Leerzeichen geprinted

**Comment by felixauringer** [comment]
Bei mir passiert das nicht und auch die Tests sagen etwas anderes. Koenntest Du beschreiben, wie man den Bug reproduzieren kann (Branch, Test-String, Startknoten, ...)?

**Comment by T4rikA** [comment]
Circumflex in Blöcken geht noch kaputt `[ ^ test ]`
