### ISSUE TITLE
Search window no syntax highlighting

### ISSUE THREAD

**Issue by T4rikA** [hpi-swa-teaching/OhmPrettyPrint#36]
If you search a method in Squeak, there is no syntax highlighting
MessageNamesContaining

**Comment by felixauringer** [comment]
Was genau meinst Du? Oben rechts das Suchfeld (Ctrl + 0)? Wenn ja, was hat das mit unserem Projekt zu tun?

**Comment by Paula-Kli** [comment]
In anderen Browser Fenstern, außer dem normalen Systembrowser gibt es kein Syntaxhighlighting, wenn man OmegaPrint auswählt
