### ISSUE TITLE
KeywordMessages in Kaskaden umbrechen

### ISSUE THREAD

**Issue by Paula-Kli** [hpi-swa-teaching/OhmPrettyPrint#47]
in Kaskaden werden KeywordMessages nicht umgebrochen
self foo: 1 bar: 2 buz: 4; foo2: 3 bar4: 4
dort ausprobieren

**Comment by felixauringer** [comment]
Umbrueche gibt es bisher nur in `KeywordMessageSend`. Da Kaskaden aber auf `MessageChain`s aufbauen, welche (transitiv) nur `KeywordMessageSegments` enthalten, sind in diesem Fall also gar keine Umbrueche zu erwarten.
