### ISSUE TITLE
Formatierung von BinaryMessages

### ISSUE THREAD

**Issue by felixauringer** [hpi-swa-teaching/OhmPrettyPrint#55]
Ich habe gerade eine Testmethode mit OmegaPrint formatiert und das folgende interessante Ergebnis erhalten:

![screenshot](https://user-images.githubusercontent.com/48409110/86445909-79941e80-bd13-11ea-9ff8-c9666895ae0e.png)

Reproduzieren laesst sich das zum Beispiel mit `3-6` startend bei `Expression`.
Da es funktioniert, wenn man `+` durch `-` ersetzt, scheint es an dem `binarySelectorChar` `-` zu liegen.

Scheint ein Problem mit der Grammatik zu sein, es wird nicht als Message, sondern als `normalFloatingPointLiteral` mit Exponent.
TODO:
- [x] Issue bei Ohm erstellen

**Comment by Paula-Kli** [comment]
Funktioniert jetzt
