### ISSUE TITLE
Kommentare in Methoden

### ISSUE THREAD

**Issue by felixauringer** [hpi-swa-teaching/OhmPrettyPrint#64]
Als Squeakentwickler möchte ich Kommentare in der Methode erhalten, da ich diese beabsichtigt zu näheren Erläuterung geschrieben habe.
13

**Comment by T4rikA** [comment]
Kommentare werden erhalten und formatiert. Diese User Story konnte nicht mehr von unserem Kunden abgenommen werden. Für zukünftige Projekte könnte man hier ansetzen und sie abnehmen lassen.
