### ISSUE TITLE
Namen von Testmethoden ueberarbeiten

### ISSUE THREAD

**Issue by felixauringer** [hpi-swa-teaching/OhmPrettyPrint#66]
An manchen Stellen sind unsere Testmethoden nicht konsistent. @T4rikA hat zum Beispiel in #54
- `TestBlockLiteral >> testWithArgumentsWithoutLocalVariablesWithMultipleLines`
- `TestBlockLiteral >> testWithArgumentsWithoutLocalVariablesWithSingleLine`
angemerkt. Das sollte in eine eigene Pull-Request, weil Aenderungen an Methodennamen in Squeak immer eine Methode loeschen, eine hinzufuegen und noch die `methodProperties.json` angepasst wird.
- `TestUnaryMessage>>testWithSelector`

Folgendes ist zu tun:
- [x] Standards im Wiki ueberarbeiten
- [x] alle Testmethoden durchgehen und gegebenenfalls anpassen

**Comment by Paula-Kli** [comment]
@felixauringer was muss hier noch gemacht werden?

**Comment by felixauringer** [comment]
> @felixauringer was muss hier noch gemacht werden?

Hm, weiß ich jetzt so auch nicht, würde mir das Montag oder Dienstag angucken, ob alle Namen den Standards im Wiki entsprechen und dann entweder das Issue schliessen oder eine PR aufmachen.

**Comment by felixauringer** [comment]
Habe gerade nochmal reingeguckt und wuerde das hier noch nicht closen. Direkt die ersten beiden Testklassen (alphabetisch) sind schon inkonsistent:
`testWithBindableIdentifierWithAssignmentOperator` und `testWithSelectorWithArgument`
Ich wuerde dafuer plaedieren (so wie beim ersten) immer die Knoten auszuschreiben, weil das immer eindeutig ist und damit auch konsistent sein sollte.
