### ISSUE TITLE
If-Abfragen überarbeiten

### ISSUE THREAD

**Issue by PatriciaSowa** [hpi-swa-teaching/OhmPrettyPrint#86]
Oftmals lösen wir Sonderfälle durch if-Abfragen.
Wir sollten versuchen diese wenn möglich zu entfernen.

**Comment by felixauringer** [comment]
Wir haben momentan noch folgende if's drin:
- `KeywordMessage:with:`
- `value:`
- `include:between:and:`
- `join:separatedBy:`
- `keywordMessageWith:and:`
- `separatorAfterHeaderWith:and:`
- `separatorInBlockWith:and:and:`
- `defaultExpression:`

Man muss sagen in `KeywordMessage` ist das ziemlich unschoen, aber mir ist bisher nichts besseres eingefallen. Die anderen sind glaube ich kaum vermeidbar.
