### ISSUE TITLE
Benennung von lokalen Variablen in Methoden

### ISSUE THREAD

**Issue by Paula-Kli** [hpi-swa-teaching/OhmPrettyPrint#92]
wann nutzen wir result, wann localVariableList und wann pragmasResult als lokale Variablen in den Methoden

**Comment by T4rikA** [comment]
Ich wäre dafür, dass wir result nutzen, wenn wir nur eins brauchen und sonst immer spezifizieren für was das ist, also bei zwei: listResult und pragmasResult und dann da nie nur result vorkommt

**Comment by Paula-Kli** [comment]
Patricias Vorschlag:
In MethodDeclaration: auch commentResult?
MoreExecutableCode: finalStatementResult?

**Comment by PatriciaSowa** [comment]
Weitere Anmerkungen:
lastComment: ich finde hier node verwirrend, wenn wir da einen cst bekommen 
space before Code: ich würde lines in lineNumber oder so umbenennen
